"""
Hubble Advanced Mining Routine (HAMR)
Designed for use with star catalogs generated by HST program GO-17776
Author: Sean K. Terry
"""

import math
import re
import numpy as np
from astropy.table import Table, Column
import astropy.units as u
import matplotlib.pyplot as plt
 
 
# =============================================================================
# CoordinateParser class — parses and converts equatorial or decimal input
# =============================================================================
 
class CoordinateParser:
    """
    Parses a user-supplied coordinate string for RA or DEC and converts it
    to decimal degrees.
 
    Accepted formats
    ----------------
    Decimal degrees  (any axis):
        "266.405"        →  266.405°
        "-29.007"        →  -29.007°
 
    RA in hours–minutes–seconds (sexagesimal):
        "17h 43m 37.2s"  →  decimal degrees
        "17:43:37.2"     →  decimal degrees   (colon-separated)
        "17 43 37.2"     →  decimal degrees   (space-separated)
 
    DEC in degrees–arcminutes–arcseconds (sexagesimal):
        "-29d 00m 25s"   →  decimal degrees
        "-29:00:25"      →  decimal degrees
        "-29 00 25"      →  decimal degrees
 
    The parser auto-detects the format:
      - Presence of 'h'/'m'/'s' letters  →  HMS (RA)
      - Presence of 'd'/'m'/'s' letters  →  DMS (DEC)
      - Colons or spaces between numbers →  HMS if called as RA, DMS if DEC
      - Plain float string               →  decimal degrees
    """
 
    # Regex: captures an optional leading sign + three numeric groups
    _SEXA_RE = re.compile(
        r"([+-]?)\s*(\d+)[hd°:\s]\s*(\d+)[m':\s]\s*([\d.]+)[s\"]?"
    )
 
    @staticmethod
    def parse_ra(raw: str) -> float:
        """
        Parse a raw RA string and return decimal degrees in [0, 360).
 
        Args:
            raw : User-supplied RA string.
 
        Returns:
            RA in decimal degrees.
 
        Raises:
            ValueError : If the string cannot be parsed or is out of range.
        """
        raw = raw.strip()
 
        # --- Try plain decimal first ---
        try:
            deg = float(raw)
            if not (0 <= deg < 360):
                raise ValueError(f"RA decimal degrees must be in [0, 360). Got: {deg}")
            return deg
        except ValueError as plain_err:
            if "must be" in str(plain_err):
                raise   # Re-raise our own range error
 
        # --- Sexagesimal ---
        # If 'd' present without 'h', treat as decimal degrees accidentally
        has_h = "h" in raw.lower()
        has_d = "d" in raw.lower() and "h" not in raw.lower()
 
        if has_d:
            # Looks like a DMS string passed as RA — interpret as decimal deg
            try:
                return CoordinateParser._dms_to_deg(raw)
            except Exception:
                pass
 
        # Default: try HMS
        try:
            return CoordinateParser._hms_to_deg(raw)
        except Exception:
            raise ValueError(
                f"Could not parse RA '{raw}'.\n"
                "  Accepted formats: '266.405'  or  '17h 43m 37.2s'  or  '17:43:37.2'"
            )
 
    @staticmethod
    def parse_dec(raw: str) -> float:
        """
        Parse a raw DEC string and return decimal degrees in [-90, 90].
 
        Args:
            raw : User-supplied DEC string.
 
        Returns:
            DEC in decimal degrees.
 
        Raises:
            ValueError : If the string cannot be parsed or is out of range.
        """
        raw = raw.strip()
 
        # --- Try plain decimal first ---
        try:
            deg = float(raw)
            if not (-90 <= deg <= 90):
                raise ValueError(f"DEC decimal degrees must be in [-90, 90]. Got: {deg}")
            return deg
        except ValueError as plain_err:
            if "must be" in str(plain_err):
                raise
 
        # --- Sexagesimal DMS ---
        try:
            deg = CoordinateParser._dms_to_deg(raw)
        except Exception:
            raise ValueError(
                f"Could not parse DEC '{raw}'.\n"
                "  Accepted formats: '-29.007'  or  '-29d 00m 25s'  or  '-29:00:25'"
            )
 
        if not (-90 <= deg <= 90):
            raise ValueError(f"DEC must be in [-90, 90]. Got: {deg}")
        return deg
 
    # ------------------------------------------------------------------
    # Private conversion helpers
    # ------------------------------------------------------------------
 
    @staticmethod
    def _hms_to_deg(raw: str) -> float:
        """Convert an H:M:S string to decimal degrees (1 hour = 15°)."""
        # Normalise separators so regex can match
        normalised = raw.strip().replace("h", ":").replace("m", ":").replace("s", "")
        parts = re.split(r"[:\s]+", normalised.strip())
        if len(parts) < 2:
            raise ValueError(f"Not enough components in HMS string: '{raw}'")
 
        sign = -1 if normalised.lstrip().startswith("-") else 1
        h    = abs(float(parts[0]))
        m    = float(parts[1]) if len(parts) > 1 else 0.0
        s    = float(parts[2]) if len(parts) > 2 else 0.0
 
        if not (0 <= m < 60) or not (0 <= s < 60):
            raise ValueError(f"Minutes/seconds out of range in '{raw}'")
 
        hours = h + m / 60 + s / 3600
        deg   = sign * hours * 15.0        # 1 hour = 15 degrees
 
        # Wrap into [0, 360)
        deg = deg % 360
        return deg
 
    @staticmethod
    def _dms_to_deg(raw: str) -> float:
        """Convert a D:M:S string to decimal degrees."""
        normalised = raw.strip().replace("d", ":").replace("°", ":") \
                               .replace("m", ":").replace("'", ":") \
                               .replace("s", "").replace('"', "")
        # Preserve leading sign before splitting
        sign = -1 if normalised.lstrip().startswith("-") else 1
        parts = re.split(r"[:\s]+", normalised.strip().lstrip("+-"))
        if len(parts) < 2:
            raise ValueError(f"Not enough components in DMS string: '{raw}'")
 
        d = float(parts[0])
        m = float(parts[1]) if len(parts) > 1 else 0.0
        s = float(parts[2]) if len(parts) > 2 else 0.0
 
        if not (0 <= m < 60) or not (0 <= s < 60):
            raise ValueError(f"Arcminutes/arcseconds out of range in '{raw}'")
 
        return sign * (d + m / 60 + s / 3600)
 
    @staticmethod
    def format_summary(ra_deg: float, dec_deg: float) -> str:
        """Return a human-readable string showing both decimal and HMS/DMS."""
        # RA → HMS
        total_h = ra_deg / 15.0
        h  = int(total_h)
        rm = (total_h - h) * 60
        m  = int(rm)
        s  = (rm - m) * 60
        ra_hms = f"{h:02d}h {m:02d}m {s:05.2f}s"
 
        # DEC → DMS
        sign    = "-" if dec_deg < 0 else "+"
        abs_dec = abs(dec_deg)
        d  = int(abs_dec)
        rm = (abs_dec - d) * 60
        am = int(rm)
        as_ = (rm - am) * 60
        dec_dms = f"{sign}{d:02d}° {am:02d}' {as_:05.2f}\""
 
        return (f"RA  = {ra_deg:.6f}°  ({ra_hms})\n"
                f"  DEC = {dec_deg:+.6f}°  ({dec_dms})")
 
 
# =============================================================================
# StarCatalog class
# =============================================================================
 
class StarCatalog:
    """
    Loads an HST bulge survey FITS catalog and supports cone search queries.
 
    Attributes:
        filepath : Path to the FITS file.
        _table   : The raw Astropy Table loaded from the file.
    """
 
    def __init__(self, filepath: str):
        """
        Initialize and load the catalog from a FITS file.
 
        Args:
            filepath : Path to the .fits catalog file.
        """
        self.filepath = filepath
        self._table   = None
        self._load()
 
    # ------------------------------------------------------------------
    # Private: loading
    # ------------------------------------------------------------------
 
    def _load(self) -> None:
        """Read the FITS file into an Astropy Table."""
        print(f"\nLoading catalog: {self.filepath} ...")
        self._table = Table.read(self.filepath)
        print(f"  → {self.star_count:,} sources loaded.")
        print(f"  → Columns: {self._table.colnames}\n")
 
    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------
 
    @property
    def star_count(self) -> int:
        """Total number of sources in the catalog (read-only)."""
        return len(self._table)
 
    # ------------------------------------------------------------------
    # Core: cone search
    # ------------------------------------------------------------------
 
    def cone_search(self, ra: float, dec: float, radius: float) -> Table:
        """
        Return all catalog sources within a cone on the sky.
 
        The returned table contains every original catalog column, plus a
        new 'distance' column (degrees) giving each source's angular
        separation from (ra, dec). The table is sorted nearest-first.
 
        Args:
            ra     : Right Ascension of the search center (decimal degrees, 0–360)
            dec    : Declination of the search center (decimal degrees, -90 to +90)
            radius : Search radius in decimal degrees (must be > 0)
 
        Returns:
            An astropy.table.Table of matching sources, sorted by 'distance'.
 
        Raises:
            ValueError : If ra, dec, or radius are outside valid ranges.
        """
        # --- Input validation ---
        if not (0 <= ra < 360):
            raise ValueError(f"RA must be in [0, 360). Got: {ra}")
        if not (-90 <= dec <= 90):
            raise ValueError(f"DEC must be in [-90, 90]. Got: {dec}")
        if radius <= 0:
            raise ValueError(f"Search radius must be > 0. Got: {radius}")
 
        # --- Vectorised Haversine over the whole catalog ---
        # Working in radians on numpy arrays is much faster than a Python loop
        ra1  = np.radians(self._table["RA"].data.astype(float))
        dec1 = np.radians(self._table["DEC"].data.astype(float))
        ra2  = math.radians(ra)
        dec2 = math.radians(dec)
 
        d_ra  = ra2  - ra1
        d_dec = dec2 - dec1
 
        a = (np.sin(d_dec / 2) ** 2
             + np.cos(dec1) * math.cos(dec2) * np.sin(d_ra / 2) ** 2)
 
        separations = np.degrees(2 * np.arcsin(np.sqrt(a)))   # degrees
 
        # --- Filter to sources inside the cone ---
        inside = separations <= radius
        result = self._table[inside].copy()
 
        # --- Add the distance column (arcseconds) ---
        dist_col = Column(
            data        = separations[inside] * 3600.0,
            name        = "distance",
            unit        = u.arcsec,
            description = "Angular separation from search center (arcseconds)",
        )
        result.add_column(dist_col)
 
        # --- Sort nearest-first ---
        result.sort("distance")
 
        return result
 
    # ------------------------------------------------------------------
    # Display helpers
    # ------------------------------------------------------------------
 
    def print_summary(self, result: Table, ra: float, dec: float,
                      radius: float) -> None:
        """Print a summary header and a short preview of the result table."""
        print()
        print("=" * 70)
        print("  Cone Search Results")
        print(f"  Center  : {CoordinateParser.format_summary(ra, dec)}")
        print(f"  Radius  : {radius * 3600:.4f} arcsec")
        print(f"  Matches : {len(result)}")
        print("=" * 70)
 
        if len(result) == 0:
            print("  No sources found in this region.\n")
            return
 
        # Show a readable preview (first 20 rows, key columns)
        preview_cols = ["HST_ID", "RA", "DEC", "F606W_Vegamag",
                        "F814W_Vegamag", "HST_Field", "distance"]
        available = [c for c in preview_cols if c in result.colnames]
        print(result[available][:20])
 
        if len(result) > 20:
            print(f"  ... and {len(result) - 20} more rows.")
 
        print()
 
    def plot_cmd(self, result: Table, ra: float, dec: float,
                 radius_arcsec: float) -> None:
        """
        Plot a colour-magnitude diagram (CMD) for the cone search results
        and save it as a PNG file.
 
        X-axis : F606W − F814W  (colour)
        Y-axis : F814W          (magnitude, inverted so brighter stars are higher)
 
        Stars missing either magnitude are silently excluded from the plot.
 
        Args:
            result        : Astropy Table returned by cone_search().
            ra            : Search centre RA (decimal degrees)  — used in filename/title.
            dec           : Search centre DEC (decimal degrees) — used in filename/title.
            radius_arcsec : Search radius in arcseconds         — used in filename/title.
        """
        if len(result) == 0:
            print("  No stars to plot.")
            return
 
        # --- Extract magnitudes, masking missing values ---
        f606w = np.array(result["F606W_Vegamag"].data.astype(float))
        f814w = np.array(result["F814W_Vegamag"].data.astype(float))
 
        valid = np.isfinite(f606w) & np.isfinite(f814w)
        n_valid = valid.sum()
 
        if n_valid == 0:
            print("  No stars with valid F606W and F814W magnitudes — skipping CMD plot.")
            return
 
        color = f606w[valid] - f814w[valid]   # F606W − F814W
        mag   = f814w[valid]                  # F814W
 
        # --- Plot ---
        fig, ax = plt.subplots(figsize=(6, 8))
 
        ax.scatter(
            color, mag,
            s       = 8,          # marker size
            alpha   = 0.6,
            color   = "steelblue",
            edgecolors = "none",
        )
 
        # Invert Y-axis: brighter (lower magnitude number) at the top
        ax.invert_yaxis()
 
        # Labels and title
        ax.set_xlabel("F606W − F814W  (mag)", fontsize=12)
        ax.set_ylabel("F814W  (Vegamag)", fontsize=12)
        ax.set_title(
            f"CMD — cone search\n"
            f"RA={ra:.6f}°  DEC={dec:+.6f}°  r={radius_arcsec:.2f}\"  "
            f"({n_valid} stars)",
            fontsize=10,
        )
 
        ax.grid(True, linestyle="--", alpha=0.4)
        fig.tight_layout()
 
        # --- Save ---
        out_name = (f"cmd_ra{ra:.6f}_dec{dec:.6f}"
                    f"_r{radius_arcsec:.4f}arcsec.png")
        fig.savefig(out_name, dpi=150)
        plt.close(fig)
        print(f"  CMD saved → {out_name}")
 
    # ------------------------------------------------------------------
    # Dunder methods
    # ------------------------------------------------------------------
 
    def __repr__(self) -> str:
        return f"StarCatalog(filepath={self.filepath!r}, stars={self.star_count:,})"
 
    def __str__(self) -> str:
        return f"HST Bulge Survey Catalog — {self.star_count:,} sources  [{self.filepath}]"
 
 
# =============================================================================
# Helper: safe user input
# =============================================================================
 
def get_float_input(prompt: str, min_val: float = None, max_val: float = None) -> float:
    """Prompt the user for a float, repeating until the input is valid."""
    while True:
        try:
            value = float(input(prompt))
            if min_val is not None and value < min_val:
                print(f"  Must be >= {min_val}. Try again.")
                continue
            if max_val is not None and value > max_val:
                print(f"  Must be <= {max_val}. Try again.")
                continue
            return value
        except ValueError:
            print("  Invalid — please enter a number.")
 
 
# =============================================================================
# Main
# =============================================================================
 
def main():
    print()
    print("╔══════════════════════════════════════════════════╗")
    print("║    HST Bulge Survey — Cone Search Query Tool     ║")
    print("╚══════════════════════════════════════════════════╝")
 
    # --- Load catalog ---
    fits_path = input("\nPath to FITS catalog file: ").strip()
    try:
        catalog = StarCatalog(fits_path)
    except FileNotFoundError:
        print(f"  Error: file not found — {fits_path}")
        return
    except Exception as e:
        print(f"  Error loading catalog: {e}")
        return
 
    print(catalog)
 
    # --- Interactive query loop ---
    while True:
        print("\nEnter search parameters (Ctrl-C to quit):")
        print("  Coordinates may be decimal degrees  e.g.  266.405  /  -29.007")
        print("  or equatorial (HMS / DMS)            e.g.  17h43m37s  /  -29d00m25s")
        print("  or colon-separated                   e.g.  17:43:37   /  -29:00:25")
        print()
 
        # RA
        while True:
            try:
                ra = CoordinateParser.parse_ra(input("  RA  : ").strip())
                break
            except ValueError as e:
                print(f"  Error: {e}")
 
        # DEC
        while True:
            try:
                dec = CoordinateParser.parse_dec(input("  DEC : ").strip())
                break
            except ValueError as e:
                print(f"  Error: {e}")
 
        # Confirm what was parsed
        print(f"\n  Parsed → {CoordinateParser.format_summary(ra, dec)}")
 
        radius_arcsec = get_float_input("  Radius (arcseconds, > 0) : ", 1e-9)
        radius = radius_arcsec / 3600.0   # convert to degrees for cone_search()
 
        try:
            results = catalog.cone_search(ra, dec, radius)
            catalog.print_summary(results, ra, dec, radius)
        except ValueError as e:
            print(f"\n  Error: {e}")
            continue
 
        # --- Optional: save to file ---
        if len(results) > 0:
            save = input("  Save results to a file? (y/n): ").strip().lower()
            if save == "y":
                fmt = input("  Format — fits / csv / ecsv [default: fits]: ").strip().lower()
                fmt = fmt if fmt in ("fits", "csv", "ecsv") else "fits"
                out_name = f"cone_search_ra{ra:.6f}_dec{dec:.6f}_r{radius_arcsec:.4f}arcsec.{fmt}"
                results.write(out_name, overwrite=True)
                print(f"  Saved → {out_name}")
 
            plot = input("  Plot colour-magnitude diagram? (y/n): ").strip().lower()
            if plot == "y":
                catalog.plot_cmd(results, ra, dec, radius_arcsec)
 
        again = input("\nRun another search? (y/n): ").strip().lower()
        if again != "y":
            break
 
    print("\nGoodbye!\n")
 
 
if __name__ == "__main__":
    main()
