"""
Hubble Advanced Mining Routine for Roman (HAMRR)
Designed for use with star catalogs generated by HST program GO-17776
Authors: Sean K. Terry, Claude (Anthropic)
"""

import math
import re
import numpy as np
from astropy.table import Table, Column
import astropy.units as u
import matplotlib.pyplot as plt

# MAST image search and cutout — handled by the companion module
from image_cut import get_mast_cutout


# =============================================================================
# CoordinateParser class — parses and converts equatorial or decimal input
# =============================================================================

class CoordinateParser:
    """
    Parses a user-supplied coordinate string for RA or DEC and converts it
    to decimal degrees.

    Accepted formats
    ----------------
    Decimal degrees  (any axis):
        "266.405"        →  266.405°
        "-29.007"        →  -29.007°

    RA in hours–minutes–seconds (sexagesimal):
        "17h 43m 37.2s"  →  decimal degrees
        "17:43:37.2"     →  decimal degrees   (colon-separated)
        "17 43 37.2"     →  decimal degrees   (space-separated)

    DEC in degrees–arcminutes–arcseconds (sexagesimal):
        "-29d 00m 25s"   →  decimal degrees
        "-29:00:25"      →  decimal degrees
        "-29 00 25"      →  decimal degrees

    The parser auto-detects the format:
      - Presence of 'h'/'m'/'s' letters  →  HMS (RA)
      - Presence of 'd'/'m'/'s' letters  →  DMS (DEC)
      - Colons or spaces between numbers →  HMS if called as RA, DMS if DEC
      - Plain float string               →  decimal degrees
    """

    # Regex: captures an optional leading sign + three numeric groups
    _SEXA_RE = re.compile(
        r"([+-]?)\s*(\d+)[hd°:\s]\s*(\d+)[m':\s]\s*([\d.]+)[s\"]?"
    )

    @staticmethod
    def parse_ra(raw: str) -> float:
        """
        Parse a raw RA string and return decimal degrees in [0, 360).

        Args:
            raw : User-supplied RA string.

        Returns:
            RA in decimal degrees.

        Raises:
            ValueError : If the string cannot be parsed or is out of range.
        """
        raw = raw.strip()

        # --- Try plain decimal first ---
        try:
            deg = float(raw)
            if not (0 <= deg < 360):
                raise ValueError(f"RA decimal degrees must be in [0, 360). Got: {deg}")
            return deg
        except ValueError as plain_err:
            if "must be" in str(plain_err):
                raise   # Re-raise our own range error

        # --- Sexagesimal ---
        # If 'd' present without 'h', treat as decimal degrees accidentally
        has_h = "h" in raw.lower()
        has_d = "d" in raw.lower() and "h" not in raw.lower()

        if has_d:
            # Looks like a DMS string passed as RA — interpret as decimal deg
            try:
                return CoordinateParser._dms_to_deg(raw)
            except Exception:
                pass

        # Default: try HMS
        try:
            return CoordinateParser._hms_to_deg(raw)
        except Exception:
            raise ValueError(
                f"Could not parse RA '{raw}'.\n"
                "  Accepted formats: '266.405'  or  '17h 43m 37.2s'  or  '17:43:37.2'"
            )

    @staticmethod
    def parse_dec(raw: str) -> float:
        """
        Parse a raw DEC string and return decimal degrees in [-90, 90].

        Args:
            raw : User-supplied DEC string.

        Returns:
            DEC in decimal degrees.

        Raises:
            ValueError : If the string cannot be parsed or is out of range.
        """
        raw = raw.strip()

        # --- Try plain decimal first ---
        try:
            deg = float(raw)
            if not (-90 <= deg <= 90):
                raise ValueError(f"DEC decimal degrees must be in [-90, 90]. Got: {deg}")
            return deg
        except ValueError as plain_err:
            if "must be" in str(plain_err):
                raise

        # --- Sexagesimal DMS ---
        try:
            deg = CoordinateParser._dms_to_deg(raw)
        except Exception:
            raise ValueError(
                f"Could not parse DEC '{raw}'.\n"
                "  Accepted formats: '-29.007'  or  '-29d 00m 25s'  or  '-29:00:25'"
            )

        if not (-90 <= deg <= 90):
            raise ValueError(f"DEC must be in [-90, 90]. Got: {deg}")
        return deg

    # ------------------------------------------------------------------
    # Private conversion helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _hms_to_deg(raw: str) -> float:
        """Convert an H:M:S string to decimal degrees (1 hour = 15°)."""
        # Normalise separators so regex can match
        normalised = raw.strip().replace("h", ":").replace("m", ":").replace("s", "")
        parts = re.split(r"[:\s]+", normalised.strip())
        if len(parts) < 2:
            raise ValueError(f"Not enough components in HMS string: '{raw}'")

        sign = -1 if normalised.lstrip().startswith("-") else 1
        h    = abs(float(parts[0]))
        m    = float(parts[1]) if len(parts) > 1 else 0.0
        s    = float(parts[2]) if len(parts) > 2 else 0.0

        if not (0 <= m < 60) or not (0 <= s < 60):
            raise ValueError(f"Minutes/seconds out of range in '{raw}'")

        hours = h + m / 60 + s / 3600
        deg   = sign * hours * 15.0        # 1 hour = 15 degrees

        # Wrap into [0, 360)
        deg = deg % 360
        return deg

    @staticmethod
    def _dms_to_deg(raw: str) -> float:
        """Convert a D:M:S string to decimal degrees."""
        normalised = raw.strip().replace("d", ":").replace("°", ":") \
                               .replace("m", ":").replace("'", ":") \
                               .replace("s", "").replace('"', "")
        # Preserve leading sign before splitting
        sign = -1 if normalised.lstrip().startswith("-") else 1
        parts = re.split(r"[:\s]+", normalised.strip().lstrip("+-"))
        if len(parts) < 2:
            raise ValueError(f"Not enough components in DMS string: '{raw}'")

        d = float(parts[0])
        m = float(parts[1]) if len(parts) > 1 else 0.0
        s = float(parts[2]) if len(parts) > 2 else 0.0

        if not (0 <= m < 60) or not (0 <= s < 60):
            raise ValueError(f"Arcminutes/arcseconds out of range in '{raw}'")

        return sign * (d + m / 60 + s / 3600)

    @staticmethod
    def format_summary(ra_deg: float, dec_deg: float) -> str:
        """Return a human-readable string showing both decimal and HMS/DMS."""
        # RA → HMS
        total_h = ra_deg / 15.0
        h  = int(total_h)
        rm = (total_h - h) * 60
        m  = int(rm)
        s  = (rm - m) * 60
        ra_hms = f"{h:02d}h {m:02d}m {s:05.2f}s"

        # DEC → DMS
        sign    = "-" if dec_deg < 0 else "+"
        abs_dec = abs(dec_deg)
        d  = int(abs_dec)
        rm = (abs_dec - d) * 60
        am = int(rm)
        as_ = (rm - am) * 60
        dec_dms = f"{sign}{d:02d}° {am:02d}' {as_:05.2f}\""

        return (f"RA  = {ra_deg:.6f}°  ({ra_hms})\n"
                f"  DEC = {dec_deg:+.6f}°  ({dec_dms})")


# =============================================================================
# StarCatalog class
# =============================================================================

class StarCatalog:
    """
    Loads an HST bulge survey FITS catalog and supports cone search queries.

    Attributes:
        filepath : Path to the FITS file.
        _table   : The raw Astropy Table loaded from the file.
    """

    def __init__(self, filepath: str):
        """
        Initialize and load the catalog from a FITS file.

        Args:
            filepath : Path to the .fits catalog file, or a .zip archive containing one.
        """
        self.filepath = filepath
        self._table   = None
        self._load()

    # ------------------------------------------------------------------
    # Private: loading
    # ------------------------------------------------------------------

    def _load(self) -> None:
        """
        Read the catalog into an Astropy Table.
        Accepts either a plain .fits file or a .zip archive containing one.
        The zip is decompressed directly into memory - nothing is written to disk.
        """
        #print(f"\nLoading catalog: {self.filepath} ...")

        if self.filepath.lower().endswith(".zip"):
            import zipfile
            with zipfile.ZipFile(self.filepath) as zf:
                fits_entries = [n for n in zf.namelist()
                                if n.lower().endswith(".fits")]
                if not fits_entries:
                    raise ValueError(
                        f"No .fits file found inside '{self.filepath}'."
                    )
                fits_name = fits_entries[0]
                #print(f"  Reading '{fits_name}' from zip ...")
                with zf.open(fits_name) as f:
                    self._table = Table.read(f)
        else:
            self._table = Table.read(self.filepath)

        #print(f"  {self.star_count:,} sources loaded.")
        #print(f"  Columns: {self._table.colnames}\n")

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def star_count(self) -> int:
        """Total number of sources in the catalog (read-only)."""
        return len(self._table)

    # ------------------------------------------------------------------
    # Core: cone search
    # ------------------------------------------------------------------

    def cone_search(self, ra: float, dec: float, radius: float) -> Table:
        """
        Return all catalog sources within a cone on the sky.

        The returned table contains every original catalog column, plus a
        new 'distance' column (degrees) giving each source's angular
        separation from (ra, dec). The table is sorted nearest-first.

        Args:
            ra     : Right Ascension of the search center (decimal degrees, 0–360)
            dec    : Declination of the search center (decimal degrees, -90 to +90)
            radius : Search radius in decimal degrees (must be > 0)

        Returns:
            An astropy.table.Table of matching sources, sorted by 'distance'.

        Raises:
            ValueError : If ra, dec, or radius are outside valid ranges.
        """
        # --- Input validation ---
        if not (0 <= ra < 360):
            raise ValueError(f"RA must be in [0, 360). Got: {ra}")
        if not (-90 <= dec <= 90):
            raise ValueError(f"DEC must be in [-90, 90]. Got: {dec}")
        if radius <= 0:
            raise ValueError(f"Search radius must be > 0. Got: {radius}")

        # --- Vectorised Haversine over the whole catalog ---
        # Working in radians on numpy arrays is much faster than a Python loop
        ra1  = np.radians(self._table["RA"].data.astype(float))
        dec1 = np.radians(self._table["DEC"].data.astype(float))
        ra2  = math.radians(ra)
        dec2 = math.radians(dec)

        d_ra  = ra2  - ra1
        d_dec = dec2 - dec1

        a = (np.sin(d_dec / 2) ** 2
             + np.cos(dec1) * math.cos(dec2) * np.sin(d_ra / 2) ** 2)

        separations = np.degrees(2 * np.arcsin(np.sqrt(a)))   # degrees

        # --- Filter to sources inside the cone ---
        inside = separations <= radius
        result = self._table[inside].copy()

        # --- Add the distance column (arcseconds) ---
        dist_col = Column(
            data        = separations[inside] * 3600.0,
            name        = "distance",
            unit        = u.arcsec,
            description = "Angular separation from search center (arcseconds)",
        )
        result.add_column(dist_col)

        # --- Sort nearest-first ---
        result.sort("distance")

        return result

    # ------------------------------------------------------------------
    # Display helpers
    # ------------------------------------------------------------------

    def print_summary(self, result: Table, ra: float, dec: float,
                      radius: float) -> None:
        """Print a summary header and a short preview of the result table."""
        print()
        print("=" * 70)
        print("  Search Results")
        print(f"  Center  : {CoordinateParser.format_summary(ra, dec)}")
        print(f"  Radius  : {radius * 3600:.4f} arcsec")
        print(f"  Matches : {len(result)}")
        print("=" * 70)

        if len(result) == 0:
            print("  No sources found in this region.\n")
            return

        # Show a readable preview (first 20 rows, key columns)
        preview_cols = ["HST_ID", "RA", "DEC", "F606W_Vegamag",
                        "F814W_Vegamag", "HST_Field", "distance"]
        available = [c for c in preview_cols if c in result.colnames]
        print(result[available][:20])

        if len(result) > 20:
            print(f"  ... and {len(result) - 20} more rows.")

        print()

    def plot_cmd(self, result: Table, ra: float, dec: float,
                 radius_arcsec: float, output_dir: str = "output") -> None:
        """
        Plot a colour-magnitude diagram (CMD) for the cone search results
        and save it as a PNG file.

        X-axis : F606W − F814W
        Y-axis : F814W

        Stars missing either magnitude are silently excluded from the plot.

        Args:
            result        : Astropy Table returned by cone_search().
            ra            : Search centre RA (decimal degrees)  — used in filename/title.
            dec           : Search centre DEC (decimal degrees) — used in filename/title.
            radius_arcsec : Search radius in arcseconds         — used in filename/title.
            output_dir    : Directory in which to save the PNG  (default: "output").
        """
        if len(result) == 0:
            print("  No stars to plot.")
            return

        # --- Extract magnitudes, masking missing values ---
        f606w = np.array(result["F606W_Vegamag"].data.astype(float))
        f814w = np.array(result["F814W_Vegamag"].data.astype(float))

        valid = np.isfinite(f606w) & np.isfinite(f814w)
        n_valid = valid.sum()

        if n_valid == 0:
            print("  No stars with valid F606W and F814W magnitudes — skipping CMD plot.")
            return

        color = f606w[valid] - f814w[valid]   # F606W − F814W
        mag   = f814w[valid]                  # F814W

        # --- Plot ---
        fig, ax = plt.subplots(figsize=(6, 8))

        ax.scatter(
            color, mag,
            s       = 8,          # marker size
            alpha   = 0.4,
            color   = "steelblue",
            edgecolors = "none",
        )

        # Invert Y-axis: brighter (lower magnitude number) at the top
        ax.invert_yaxis()

        # Labels and title
        ax.set_xlabel("F606W − F814W", fontsize=12)
        ax.set_ylabel("F814W [mag]", fontsize=12)
        ax.set_title(
            f"Color-Magnitude Diagram\n"
            f"RA={ra:.3f}°  DEC={dec:+.3f}°  r={radius_arcsec:.2f}\"  "
            f"({n_valid} stars)",
            fontsize=10,
        )

        #ax.grid(True, linestyle="--", alpha=0.3)
        fig.tight_layout()

        # --- Save ---
        import os
        os.makedirs(output_dir, exist_ok=True)
        out_name = os.path.join(output_dir,
                                f"hamrr_cmd_ra{ra:.3f}_dec{dec:.3f}"
                                f"_r{radius_arcsec:.2f}arcsec.png")
        fig.savefig(out_name, dpi=150)
        plt.close(fig)
        print(f"  CMD saved → {out_name}")


    def plot_lf(self, result: Table, ra: float, dec: float,
                radius_arcsec: float, band: str = "F814W",
                normalise: bool = False, output_dir: str = "output") -> None:
        """
        Plot a luminosity function (magnitude histogram) for the cone search
        results and save it as a PNG file.

        The luminosity function shows star counts (Y-axis) per magnitude bin
        (X-axis) for a chosen filter band. Bin width is fixed at 0.3 magnitudes.

        Stars with missing/non-finite magnitudes are silently excluded.

        Args:
            result        : Astropy Table returned by cone_search().
            ra            : Search centre RA (decimal degrees)  — used in filename/title.
            dec           : Search centre DEC (decimal degrees) — used in filename/title.
            radius_arcsec : Search radius in arcseconds         — used in filename/title.
            band          : Filter band to plot — "F814W" (default) or "F606W".
            normalise     : If True, divide counts by the cone area in arcmin²,
                            giving units of stars mag⁻¹ arcmin⁻².
                            If False (default), plot raw star counts.
            output_dir    : Directory in which to save the PNG  (default: "output").
        """
        if len(result) == 0:
            print("  No stars to plot.")
            return

        # Map band name to catalog column
        col_map = {
            "F814W": "F814W_Vegamag",
            "F606W": "F606W_Vegamag",
        }
        band = band.upper()
        if band not in col_map:
            print(f"  Unknown band '{band}' — choose F814W or F606W.")
            return

        col_name = col_map[band]
        if col_name not in result.colnames:
            print(f"  Column '{col_name}' not found in results — skipping LF plot.")
            return

        # --- Extract magnitudes, dropping missing values ---
        mags = np.array(result[col_name].data.astype(float))
        mags = mags[np.isfinite(mags)]
        n_valid = len(mags)

        if n_valid == 0:
            print(f"  No stars with valid {band} magnitudes — skipping LF plot.")
            return

        # --- Cone area (always computed; only used when normalise=True) ---
        radius_arcmin = radius_arcsec / 60.0
        area_arcmin2  = math.pi * radius_arcmin ** 2

        # --- Build histogram bins aligned to 0.3 mag intervals ---
        bin_width = 0.3
        mag_min   = np.floor(mags.min() / bin_width) * bin_width
        mag_max   = np.ceil( mags.max() / bin_width) * bin_width
        bins      = np.arange(mag_min, mag_max + bin_width, bin_width)

        counts, _   = np.histogram(mags, bins=bins)
        bin_centers = 0.5 * (bins[:-1] + bins[1:])

        # Normalise by sky area if requested, otherwise use raw counts
        if normalise:
            y_values = counts / area_arcmin2
            y_label  = r"stars / mag / arcmin$^2$"
            area_str = f"  area={area_arcmin2:.3f} arcmin²"
        else:
            y_values = counts.astype(float)
            y_label  = "Number of stars"
            area_str = ""

        # --- Plot ---
        fig, ax = plt.subplots(figsize=(7, 5))

        ax.step(
            bin_centers,
            y_values,
            color     = "royalblue",
            linewidth = 0.9,
            alpha     = 0.99,
        )

        ax.set_yscale('log')
        ax.set_xlabel(f"{band} [mag]", fontsize=12)
        ax.set_ylabel(y_label, fontsize=12)
        ax.set_title(
            f"Luminosity Function ({band})\n"
            f"RA={ra:.3f}°  DEC={dec:+.3f}°  r={radius_arcsec:.2f}\""
            f"{area_str}  ({n_valid} stars,  bin width={bin_width} mag)",
            fontsize=8,
        )

        #ax.grid(True, linestyle="--", alpha=0.3, axis="y")
        fig.tight_layout()

        # --- Save ---
        import os
        os.makedirs(output_dir, exist_ok=True)
        out_name = os.path.join(output_dir,
                                f"hamrr_lf_{band.lower()}_ra{ra:.3f}_dec{dec:.3f}"
                                f"_r{radius_arcsec:.2f}arcsec.png")
        fig.savefig(out_name, dpi=150)
        plt.close(fig)
        print(f"  LF saved → {out_name}")

    # ------------------------------------------------------------------
    # Dunder methods
    # ------------------------------------------------------------------

    def __repr__(self) -> str:
        return f"StarCatalog(filepath={self.filepath!r}, stars={self.star_count:,})"

    def __str__(self) -> str:
        return f"HST Bulge Survey Catalog — {self.star_count:,} sources  [{self.filepath}]"


# =============================================================================
# ParamFileReader class — parses a params.in file
# =============================================================================

class ParamFileReader:
    """
    Reads and validates a plain-text parameter file (params.in).

    File format
    -----------
    Each non-blank, non-comment line is a  key = value  pair.
    Lines beginning with  #  are comments and are ignored.

    Supported keys
    --------------
    catalog_path   : Path to the .fits or .zip catalog file  (required)
    ra             : Search centre RA  — decimal degrees or HMS  (required)
    dec            : Search centre DEC — decimal degrees or DMS  (required)
    radius_arcsec  : Search radius in arcseconds                 (required)
    save_results   : yes / no   — save the result table          (default: no)
    save_format    : fits / csv / ecsv                           (default: fits)
    plot_cmd       : yes / no   — generate a CMD plot            (default: no)
    plot_lf        : yes / no   — generate a luminosity function (default: no)
    lf_band        : F814W / F606W  — band for the LF plot       (default: F814W)
    lf_normalise   : yes / no   — normalise LF by sky area       (default: no)
                     yes = stars mag⁻¹ arcmin⁻² ;  no = raw star counts
    imagecut         : yes / no   — download HST cutout from MAST   (default: no)
    imagecut_pid     : HST program ID to query                      (default: 17776)
    imagecut_size    : Cutout size in pixels (square)               (default: auto)
                     If omitted or set to 'auto', the size is computed from
                     radius_arcsec and the instrument pixel scale inferred from
                     the HST_Field column of the cone-search results:
                       ACSWFC  → 50 mas/pix   size = ceil(2 * radius_arcsec / 0.050)
                       WFC3UV  → 40 mas/pix   size = ceil(2 * radius_arcsec / 0.040)
    output_dir     : Directory for all output files               (default: output)

    Example params.in
    -----------------
    # HST Bulge Survey cone search parameters
    catalog_path  = terry_hst_bulge_survey_early_fields_cat.zip
    ra            = 17:43:37.2
    dec           = -29:00:25
    radius_arcsec = 18.0
    save_results  = yes
    save_format   = csv
    plot_cmd      = yes
    plot_lf       = yes
    lf_band       = F814W
    lf_normalise  = no
    """

    # Keys that must be present
    REQUIRED = {"catalog_path", "ra", "dec", "radius_arcsec"}

    # Keys with default values when absent
    DEFAULTS = {
        "save_results":  "no",
        "save_format":   "fits",
        "plot_cmd":      "no",
        "plot_lf":       "no",
        "lf_band":       "F814W",
        "lf_normalise":  "no",
        "imagecut":        "no",
        "imagecut_pid":    "17776",
        "imagecut_size":   "auto",
        "output_dir":    "output",
    }

    def __init__(self, filepath: str = "params.in"):
        self.filepath = filepath
        self._params  = dict(self.DEFAULTS)   # start with defaults
        self._parse()

    # ------------------------------------------------------------------
    # Parsing
    # ------------------------------------------------------------------

    def _parse(self) -> None:
        """Read the file and populate self._params."""
        with open(self.filepath, "r", encoding="utf-8") as f:
            for lineno, raw in enumerate(f, start=1):
                line = raw.strip()
                if not line or line.startswith("#"):
                    continue                   # skip blank lines and comments
                if "=" not in line:
                    raise ValueError(
                        f"params.in line {lineno}: expected 'key = value', got: {raw.rstrip()!r}"
                    )
                key, _, value = line.partition("=")
                key   = key.strip().lower()
                value = value.strip()
                if not key:
                    raise ValueError(f"params.in line {lineno}: empty key.")
                self._params[key] = value

        # Check all required keys are present
        missing = self.REQUIRED - self._params.keys()
        if missing:
            raise ValueError(
                f"params.in is missing required key(s): {', '.join(sorted(missing))}"
            )

    # ------------------------------------------------------------------
    # Typed accessors
    # ------------------------------------------------------------------

    @property
    def catalog_path(self) -> str:
        return self._params["catalog_path"]

    @property
    def ra(self) -> float:
        return CoordinateParser.parse_ra(self._params["ra"])

    @property
    def dec(self) -> float:
        return CoordinateParser.parse_dec(self._params["dec"])

    @property
    def radius_arcsec(self) -> float:
        v = float(self._params["radius_arcsec"])
        if v <= 0:
            raise ValueError(f"radius_arcsec must be > 0. Got: {v}")
        return v

    @property
    def save_results(self) -> bool:
        return self._params["save_results"].lower() in ("yes", "true", "1")

    @property
    def save_format(self) -> str:
        fmt = self._params["save_format"].lower()
        if fmt not in ("fits", "csv", "ecsv"):
            raise ValueError(f"save_format must be fits / csv / ecsv. Got: {fmt!r}")
        return fmt

    @property
    def plot_cmd(self) -> bool:
        return self._params["plot_cmd"].lower() in ("yes", "true", "1")

    @property
    def plot_lf(self) -> bool:
        return self._params["plot_lf"].lower() in ("yes", "true", "1")

    @property
    def lf_band(self) -> str:
        band = self._params["lf_band"].upper()
        if band not in ("F814W", "F606W"):
            raise ValueError(f"lf_band must be F814W or F606W. Got: {band!r}")
        return band

    @property
    def lf_normalise(self) -> bool:
        return self._params["lf_normalise"].lower() in ("yes", "true", "1")

    @property
    def imagecut(self) -> bool:
        return self._params["imagecut"].lower() in ("yes", "true", "1")

    @property
    def imagecut_pid(self) -> int:
        return int(self._params["imagecut_pid"])

    @property
    def imagecut_size(self):
        """Return the cutout size in pixels, or None to trigger auto-computation."""
        raw = self._params["imagecut_size"].strip().lower()
        if raw == "auto":
            return None
        v = int(raw)
        if v <= 0:
            raise ValueError(f"imagecut_size must be > 0. Got: {v}")
        return v

    @property
    def output_dir(self) -> str:
        return self._params["output_dir"]

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    def print_summary(self) -> None:
        """Print the parsed parameters for confirmation."""
        print("  Parameters loaded from params.in:")
        for k, v in self._params.items():
            print(f"    {k:<20} = {v}")
        print()


# =============================================================================
# Helper: safe user input
# =============================================================================

def get_float_input(prompt: str, min_val: float = None, max_val: float = None) -> float:
    """Prompt the user for a float, repeating until the input is valid."""
    while True:
        try:
            value = float(input(prompt))
            if min_val is not None and value < min_val:
                print(f"  Must be >= {min_val}. Try again.")
                continue
            if max_val is not None and value > max_val:
                print(f"  Must be <= {max_val}. Try again.")
                continue
            return value
        except ValueError:
            print("  Invalid — please enter a number.")


# =============================================================================
# Main
# =============================================================================

def _auto_imagecut_size(results, radius_arcsec: float) -> int:
    """
    Compute a cutout size (pixels, square) that spans the full search diameter.

    Pixel scales used:
      ACSWFC  → 50 mas/pix
      WFC3UV  → 40 mas/pix
    Falls back to ACSWFC if the instrument cannot be determined.
    """
    pixel_scale = 0.050  # arcsec/pix — ACS/WFC default
    if "HST_Field" in results.colnames and len(results) > 0:
        for field_val in results["HST_Field"]:
            s = str(field_val)
            if "WFC3UV" in s:
                pixel_scale = 0.040
                break
            if "ACSWFC" in s:
                pixel_scale = 0.050
                break
    return math.ceil(2 * radius_arcsec / pixel_scale)


def run_query(catalog, ra, dec, radius_arcsec, save, fmt, do_plot, do_lf, lf_band,
              lf_normalise=False, do_imagecut=False, imagecut_pid=17776, imagecut_size=None,
              output_dir="output"):
    """
    Execute a single cone search and handle output.
    Shared by both interactive mode and param-file mode.
    """
    import os
    os.makedirs(output_dir, exist_ok=True)

    radius = radius_arcsec / 3600.0

    try:
        results = catalog.cone_search(ra, dec, radius)
        catalog.print_summary(results, ra, dec, radius)
    except ValueError as e:
        print(f"\n  Error: {e}")
        return

    if len(results) == 0:
        return

    if save:
        out_name = os.path.join(output_dir,
                                f"hamrr_ra{ra:.3f}_dec{dec:.3f}"
                                f"_r{radius_arcsec:.2f}arcsec.{fmt}")
        results.write(out_name, overwrite=True)
        print(f"  Saved -> {out_name}")

    if do_plot:
        catalog.plot_cmd(results, ra, dec, radius_arcsec, output_dir=output_dir)

    if do_lf:
        catalog.plot_lf(results, ra, dec, radius_arcsec, band=lf_band,
                        normalise=lf_normalise, output_dir=output_dir)

    if do_imagecut:
        if imagecut_size is None:
            imagecut_size = _auto_imagecut_size(results, radius_arcsec)
            print(f"  imagecut_size auto-computed: {imagecut_size} px")
        get_mast_cutout(ra, dec, program_id=imagecut_pid, size=imagecut_size,
                        output_dir=output_dir)


def main():
    import os

    print()
    print("╔══════════════════════════════════════════════════╗")
    print("║                  Starting HAMRR                  ║")
    print("╚══════════════════════════════════════════════════╝")

    # ── Decide mode: param-file or interactive ──────────────────────────
    use_params = os.path.isfile("params.in")
    if use_params:
        print("\n  params.in detected — running in parameter-file mode.")
        print("  (Delete or rename params.in to use interactive mode.)\n")
    else:
        print("\n  No params.in found — running in interactive mode.")
        print("  (Create a params.in file to run non-interactively.)\n")

    # ══════════════════════════════════════════════════════════════════════
    # PARAMETER-FILE MODE
    # ══════════════════════════════════════════════════════════════════════
    if use_params:
        try:
            p = ParamFileReader("params.in")
        except (FileNotFoundError, ValueError) as e:
            print(f"  Error reading params.in: {e}")
            return

        p.print_summary()

        try:
            catalog = StarCatalog(p.catalog_path)
        except FileNotFoundError:
            print(f"  Error: catalog file not found — {p.catalog_path}")
            return
        except Exception as e:
            print(f"  Error loading catalog: {e}")
            return

        print(catalog)

        try:
            ra            = p.ra
            dec           = p.dec
            radius_arcsec = p.radius_arcsec
        except ValueError as e:
            print(f"  Error in params.in: {e}")
            return

        #print(f"  Parsed coordinates:")
        #print(f"  {CoordinateParser.format_summary(ra, dec)}")
        #print(f"  Radius : {radius_arcsec} arcsec\n")

        run_query(catalog, ra, dec, radius_arcsec,
                  save=p.save_results, fmt=p.save_format, do_plot=p.plot_cmd,
                  do_lf=p.plot_lf, lf_band=p.lf_band, lf_normalise=p.lf_normalise,
                  do_imagecut=p.imagecut, imagecut_pid=p.imagecut_pid,
                  imagecut_size=p.imagecut_size, output_dir=p.output_dir)

    # ══════════════════════════════════════════════════════════════════════
    # INTERACTIVE MODE
    # ══════════════════════════════════════════════════════════════════════
    else:
        fits_path = input("Path to FITS catalog file: ").strip()
        try:
            catalog = StarCatalog(fits_path)
        except FileNotFoundError:
            print(f"  Error: file not found — {fits_path}")
            return
        except Exception as e:
            print(f"  Error loading catalog: {e}")
            return

        print(catalog)

        while True:
            print("\nEnter search parameters (Ctrl-C to quit):")
            print("  Coordinates may be decimal degrees  e.g.  266.405  /  -29.007")
            print("  or equatorial (HMS / DMS)            e.g.  17h43m37s  /  -29d00m25s")
            print("  or colon-separated                   e.g.  17:43:37   /  -29:00:25")
            print()

            # RA
            while True:
                try:
                    ra = CoordinateParser.parse_ra(input("  RA  : ").strip())
                    break
                except ValueError as e:
                    print(f"  Error: {e}")

            # DEC
            while True:
                try:
                    dec = CoordinateParser.parse_dec(input("  DEC : ").strip())
                    break
                except ValueError as e:
                    print(f"  Error: {e}")

            print(f"\n  Parsed -> {CoordinateParser.format_summary(ra, dec)}")

            radius_arcsec = get_float_input("  Radius (arcseconds, > 0) : ", 1e-9)

            # Output directory
            out_dir_input = input("  Output directory [default: output]: ").strip()
            output_dir = out_dir_input if out_dir_input else "output"

            # Output options
            save = input("  Save results to a file? (y/n): ").strip().lower() == "y"
            fmt  = "fits"
            if save:
                fmt_input = input("  Format — fits / csv / ecsv [default: fits]: ").strip().lower()
                fmt = fmt_input if fmt_input in ("fits", "csv", "ecsv") else "fits"

            do_plot = input("  Plot colour-magnitude diagram? (y/n): ").strip().lower() == "y"

            do_lf        = input("  Plot luminosity function? (y/n): ").strip().lower() == "y"
            lf_band      = "F814W"
            lf_normalise = False
            if do_lf:
                band_input = input("  Band for LF — F814W / F606W [default: F814W]: ").strip().upper()
                lf_band = band_input if band_input in ("F814W", "F606W") else "F814W"
                lf_normalise = input("  Normalise LF by sky area? (y/n): ").strip().lower() == "y"

            do_imagecut  = input("  Download HST image cutout from MAST? (y/n): ").strip().lower() == "y"
            imagecut_pid  = 17776
            imagecut_size = None  # auto-computed from results unless user specifies
            if do_imagecut:
                pid_input = input("  Program ID [default: 17776]: ").strip()
                if pid_input:
                    try:
                        imagecut_pid = int(pid_input)
                    except ValueError:
                        print("  Invalid program ID, using default 17776.")
                        imagecut_pid = 17776
                size_input = input("  Cutout size in pixels [auto if blank]: ").strip()
                if size_input:
                    try:
                        imagecut_size = int(size_input)
                        if imagecut_size <= 0:
                            raise ValueError
                    except ValueError:
                        print("  Invalid cutout size, will auto-compute.")
                        imagecut_size = None

            run_query(catalog, ra, dec, radius_arcsec,
                      save=save, fmt=fmt, do_plot=do_plot,
                      do_lf=do_lf, lf_band=lf_band, lf_normalise=lf_normalise,
                      do_imagecut=do_imagecut, imagecut_pid=imagecut_pid,
                      imagecut_size=imagecut_size, output_dir=output_dir)

            again = input("\nRun another search? (y/n): ").strip().lower()
            if again != "y":
                break

    print("\nGoodbye!\n")


if __name__ == "__main__":
    main()
